---
name: Hello World Github Workflow

on:
  pull_request:
    branches: [ main ]


jobs:
  build:
    name: my-java-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: My Test 1
        run: echo "run a test"
      - name: Build with Maven - My Test 2
        run: mvn clean install
      - name: Maven Testing - My Test 3 
        run: mvn test

      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
      
      - name: Cache Maven packages
      #This action allows caching dependencies and build outputs to improve workflow execution time.
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build with Maven
        run: mvn -B package -DskipTests --file pom.xml
        #Build the application using Maven
      
      - name: Upload JAR
        #This uploads artifacts from your workflow allowing you to share data between jobs and store data once a workflow is complete.
        uses: actions/upload-artifact@v3
        with:
        #Set artifact name
          name: artifact
          #From this path
          path: target/webapp-0.0.1-SNAPSHOT.jar

      - name: Download JAR
      #Download the artifact which was uploaded in the build's job
        uses: actions/download-artifact@v3
        with:
          name: artifact

      - name: Packer Validation Test
        run: export PKR_VAR_access_key=${{ secrets.AWS_ACCESS_KEY_ID }} && export PKR_VAR_secret_key=${{ secrets.AWS_SECRET_ACCESS_KEY }} && packer validate -var 'access_key=${PKR_VAR_access_key}' -var 'secret_key=${PKR_VAR_secret_key}' ami-packer.pkr.hcl

          